<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AX4A7hService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A_X4A7h' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A_X4A7h'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiere' => ['privates', '.errored..service_locator.A_X4A7h.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.A_X4A7h": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
        ], [
            'matiere' => 'App\\Entity\\Matiere',
            'entityManager' => '?',
        ]);
    }
}
