<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnseignantControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.7p79tPy.App\Controller\EnseignantController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.7p79tPy.App\\Controller\\EnseignantController::delete()'] = ($container->privates['.service_locator.7p79tPy'] ?? $container->load('get_ServiceLocator_7p79tPyService'))->withContext('App\\Controller\\EnseignantController::delete()', $container);
    }
}
