<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiliereControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sWu3q7E.App\Controller\FiliereController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sWu3q7E.App\\Controller\\FiliereController::delete()'] = ($container->privates['.service_locator.sWu3q7E'] ?? $container->load('get_ServiceLocator_SWu3q7EService'))->withContext('App\\Controller\\FiliereController::delete()', $container);
    }
}
