<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiliere2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.sWu3q7E.App\Entity\Filiere' shared service.
     *
     * @return \App\Entity\Filiere
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.sWu3q7E": it needs an instance of "App\\Entity\\Filiere" but this type has been excluded in "config/services.yaml".');
    }
}
