<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatiereControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VIvTtJP.App\Controller\MatiereController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VIvTtJP.App\\Controller\\MatiereController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'matiere' => ['privates', '.errored..service_locator.VIvTtJP.App\\Entity\\Matiere', NULL, 'Cannot autowire service ".service_locator.VIvTtJP": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".'],
        ], [
            'matiere' => 'App\\Entity\\Matiere',
        ]))->withContext('App\\Controller\\MatiereController::show()', $container);
    }
}
