<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatiereControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.A_X4A7h.App\Controller\MatiereController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.A_X4A7h.App\\Controller\\MatiereController::edit()'] = ($container->privates['.service_locator.A_X4A7h'] ?? $container->load('get_ServiceLocator_AX4A7hService'))->withContext('App\\Controller\\MatiereController::edit()', $container);
    }
}
