<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromosControllereditService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i892w8W.App\Controller\PromosController::edit()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i892w8W.App\\Controller\\PromosController::edit()'] = ($container->privates['.service_locator.i892w8W'] ?? $container->load('get_ServiceLocator_I892w8WService'))->withContext('App\\Controller\\PromosController::edit()', $container);
    }
}
