<?php

namespace ContainerBhFjSto;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalleControllerdeleteService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vnUJfl9.App\Controller\SalleController::delete()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vnUJfl9.App\\Controller\\SalleController::delete()'] = ($container->privates['.service_locator.vnUJfl9'] ?? $container->load('get_ServiceLocator_VnUJfl9Service'))->withContext('App\\Controller\\SalleController::delete()', $container);
    }
}
