<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnseignantControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j7k3Gft.App\Controller\EnseignantController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j7k3Gft.App\\Controller\\EnseignantController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enseignantRepository' => ['privates', 'App\\Repository\\EnseignantRepository', 'getEnseignantRepositoryService', true],
        ], [
            'enseignantRepository' => 'App\\Repository\\EnseignantRepository',
        ]))->withContext('App\\Controller\\EnseignantController::index()', $container);
    }
}
