<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getEnseignantControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2u88o7U.App\Controller\EnseignantController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.2u88o7U.App\\Controller\\EnseignantController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'enseignant' => ['privates', '.errored..service_locator.2u88o7U.App\\Entity\\Enseignant', NULL, 'Cannot autowire service ".service_locator.2u88o7U": it needs an instance of "App\\Entity\\Enseignant" but this type has been excluded in "config/services.yaml".'],
        ], [
            'enseignant' => 'App\\Entity\\Enseignant',
        ]))->withContext('App\\Controller\\EnseignantController::show()', $container);
    }
}
