<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFiliereControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.R0QijYN.App\Controller\FiliereController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.R0QijYN.App\\Controller\\FiliereController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'filiere' => ['privates', '.errored..service_locator.R0QijYN.App\\Entity\\Filiere', NULL, 'Cannot autowire service ".service_locator.R0QijYN": it needs an instance of "App\\Entity\\Filiere" but this type has been excluded in "config/services.yaml".'],
        ], [
            'filiere' => 'App\\Entity\\Filiere',
        ]))->withContext('App\\Controller\\FiliereController::show()', $container);
    }
}
