<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMatiere2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VIvTtJP.App\Entity\Matiere' shared service.
     *
     * @return \App\Entity\Matiere
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VIvTtJP": it needs an instance of "App\\Entity\\Matiere" but this type has been excluded in "config/services.yaml".');
    }
}
