<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPromosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3RXteeR.App\Entity\Promos' shared service.
     *
     * @return \App\Entity\Promos
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3RXteeR": it needs an instance of "App\\Entity\\Promos" but this type has been excluded in "config/services.yaml".');
    }
}
