<?php

namespace ContainerGanjQYS;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSalleControllershowService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F3eirRW.App\Controller\SalleController::show()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F3eirRW.App\\Controller\\SalleController::show()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'salle' => ['privates', '.errored..service_locator.F3eirRW.App\\Entity\\Salle', NULL, 'Cannot autowire service ".service_locator.F3eirRW": it needs an instance of "App\\Entity\\Salle" but this type has been excluded in "config/services.yaml".'],
        ], [
            'salle' => 'App\\Entity\\Salle',
        ]))->withContext('App\\Controller\\SalleController::show()', $container);
    }
}
